# Generated by Django 5.2.17 on 2026-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', '이메일'), ('wechat', '위챗 ID')], max_length=10, verbose_name='연락처 종류')),
                ('contact', models.CharField(max_length=254, verbose_name='연락처')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('age_range', models.CharField(blank=True, choices=[('under_20', '20세 미만'), ('20_24', '20~24세'), ('25_29', '25~29세'), ('30_34', '30~34세'), ('35_39', '35~39세'), ('40_plus', '40세 이상')], max_length=20, verbose_name='연령대')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='거주 도시')),
                ('visit_timing', models.CharField(blank=True, choices=[('within_1_month', '1개월 이내'), ('1_3_months', '1~3개월 후'), ('3_6_months', '3~6개월 후'), ('6_12_months', '6~12개월 후'), ('undecided', '미정')], max_length=20, verbose_name='예상 방한 시기')),
                ('stay_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='희망 체류 기간(일)')),
                ('interest_areas', models.JSONField(blank=True, default=list, verbose_name='관심 지역')),
                ('interest_services', models.JSONField(blank=True, default=list, verbose_name='관심 서비스')),
                ('budget_range', models.CharField(blank=True, choices=[('under_5k', '¥5,000 미만'), ('5k_8k', '¥5,000~8,000'), ('8k_12k', '¥8,000~12,000'), ('12k_16k', '¥12,000~16,000'), ('over_16k', '¥16,000 이상'), ('not_sure', '잘 모르겠음')], max_length=20, verbose_name='30일 패키지 지불 의향')),
                ('consent', models.BooleanField(default=False, verbose_name='개인정보 수집 동의')),
                ('language', models.CharField(choices=[('zh', '중국어 간체'), ('ko', '한국어')], default='zh', max_length=2, verbose_name='가입 시 언어')),
                ('visitor_id', models.CharField(blank=True, max_length=64, verbose_name='방문자 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 일시')),
            ],
            options={
                'verbose_name': '사전가입',
                'verbose_name_plural': '사전가입 목록',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('contact_type', 'contact'), name='unique_contact')],
            },
        ),
    ]
