# Generated by Django 5.2.17 on 2026-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('age_range', models.CharField(blank=True, choices=[('under_20', '20세 미만'), ('20_24', '20~24세'), ('25_29', '25~29세'), ('30_34', '30~34세'), ('35_39', '35~39세'), ('40_49', '40대'), ('50_plus', '50대 이상')], max_length=20, verbose_name='연령대')),
                ('countries', models.JSONField(blank=True, default=list, verbose_name='가고 싶은 나라')),
                ('stay_type', models.CharField(blank=True, choices=[('remote_work', '원격근무·프리랜서'), ('working_holiday', '워킹홀리데이·어학연수'), ('family', '가족·자녀 동반'), ('long_stay', '은퇴·롱스테이'), ('break', '휴직·쉼'), ('other', '기타')], max_length=20, verbose_name='체류 형태')),
                ('timing', models.CharField(blank=True, choices=[('within_3_months', '3개월 안'), ('3_6_months', '3~6개월 후'), ('6_12_months', '6개월~1년 후'), ('after_1_year', '1년 이후'), ('undecided', '아직 모르겠음')], max_length=20, verbose_name='이용 시기')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='관심 기능')),
                ('budget_range', models.CharField(blank=True, choices=[('under_100', '100만 원 미만'), ('100_150', '100~150만 원'), ('150_200', '150~200만 원'), ('200_300', '200~300만 원'), ('over_300', '300만 원 이상'), ('not_sure', '잘 모르겠음')], max_length=20, verbose_name='한 달 예산')),
                ('consent', models.BooleanField(default=False, verbose_name='개인정보 수집·이용 동의')),
                ('visitor_id', models.CharField(blank=True, max_length=64, verbose_name='방문자 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 일시')),
            ],
            options={
                'verbose_name': '사전가입',
                'verbose_name_plural': '사전가입 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
