# Generated by Django 5.2.17 on 2026-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_countries_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', '여성'), ('male', '남성'), ('no_answer', '밝히지 않음')], max_length=20, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='countries',
            field=models.CharField(blank=True, max_length=100, verbose_name='가 보고 싶은 곳'),
        ),
    ]
