# Generated by Django 5.2.17 on 2026-09-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', '페이지 방문'), ('cta_click', '사전가입 버튼 클릭')], max_length=20, verbose_name='이벤트')),
                ('visitor_id', models.CharField(max_length=64, verbose_name='방문자 ID')),
                ('label', models.CharField(blank=True, max_length=40, verbose_name='버튼 위치')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='경로')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='유입 경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발생 일시')),
            ],
            options={
                'verbose_name': '이벤트',
                'verbose_name_plural': '이벤트 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'visitor_id'], name='analytics_e_event_t_e0008e_idx')],
            },
        ),
    ]
